import Head from "next/head";
import HomePage from "../components/homepage/homePage";
// import { getAuthenticatedUser, getUserID } from "../utils/firebaseFunction";

const Home = () => {
  return (
    <>
      <Head>
        <title>Levantiii</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
};

export default Home;
